### ISSUE TITLE
Error in form_helper

### ISSUE THREAD

**Issue by StevenHarlow** [waynehoover/s3_direct_upload#191]
I'm getting this error:

TypeError - no implicit conversion of nil into String:
  s3_direct_upload (0.1.7) lib/s3_direct_upload/form_helper.rb:89:in `digest'

  s3_direct_upload (0.1.7) lib/s3_direct_upload/form_helper.rb:89:in `signature'

  s3_direct_upload (0.1.7) lib/s3_direct_upload/form_helper.rb:53:in `fields'

  s3_direct_upload (0.1.7) lib/s3_direct_upload/form_helper.rb:6:in `block in s3_uploader_form'

**Comment by nfedyashev** [comment]
This could be a great first pull request for any contributor. Unfortunately I don't have time to prepare a PR.

Pretty simple and yet very helpful since people are still experiencing this issue.
"Fail with a clear exception message" rather than "TypeError - no implicit conversion of nil into String:"

I suggest to reopen this issue and assign it a "good first issue" label. @StevenHarlow @mcfiredrill
